language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra
    #- add-on
    #- sys-img-armeabi-v7a-android-21

  jdk:
    - openjdk7
    - openjdk8
    - oraclejdk7
    - oraclejdk8

sudo: false

env:
  - TERM=dumb

script: ./gradlew clean test

after_success:
  #- ./gradlew jacocoTestReport
  - ./gradlew coveralls

notifications:
  slack: ccdroid:WP68r2pSWhzTk7Ya2I94WAuT

cache:
  directories:
    - $HOME/.m2
